### ISSUE TITLE
Update Auth docs

### ISSUE THREAD

**Issue by rafilong** [googleapis/python-firestore#117]
[Docs](https://googleapis.dev/python/google-api-core/latest/auth.html) currently ask to set `GOOGLE_APPLICATION_CREDENTIALS`. However, system tests require `FIRESTORE_APPLICATION_CREDENTIALS`.

**Comment by rafilong** [comment]
This is not as simple as I thought to resolve: currently the Firestore docs point to the general Auth quickstart guide, in which case `GOOGLE_APPLICATION_CREDENTIALS` is the correct environment variable. Adding a note below the [link to the Auth quickstart](https://googleapis.dev/python/firestore/latest/index.html#quick-start) is most likely sufficient, but doesn't seem like the most elegant of solutions. @crwilcox thoughts?

**Comment by tseaver** [comment]
@rafilong The system tests use a different envvar because the project configured under CI for `GOOGLE_APPLICATION_CREDENTIALS` is configured for pre-Firestore Datastore usage.  Except when running the systests, referring to the "normal" auth docs is correct (the `Client()` will pull in `GOOGLE_APPLICATION_CREDENTIALS` by default).

**Comment by rafilong** [comment]
Makes sense! Closing out then.
