### ISSUE TITLE
Ability to connect using client app configuration

### ISSUE THREAD

**Issue by LeonardoRick** [googleapis/python-firestore#309]
I really couldn't find a way to connect to this package using my application setup, not admin SDK. Is there a way to do that? This way, the access would be able to respect Firestore rules and all things related to a client access.

A solution would be to be able to connect to Client() with something like this:

```
config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com"
}

fs = Client().initialize_app(config)
```

Is there any another library or way that can do that?

**Comment by LeonardoRick** [comment]
Hi guys, thanks a lot for the project. Could you please give some feedback? I do know how to do that another way and I'm really needing this feature to my project.

It's really not a so much requested feature? I think there's no other library that does that, so probably this one should be the one that does. If you feel that is valid, I maded a **[non answered question on stackoverflow](https://stackoverflow.com/questions/66125484/connect-to-firestore-using-python-as-client-with-limited-permissions)** that I'll be very grateful if someone could help showing me the way too.

**Comment by vindard** [comment]
Linked to #314, I ran into this problem as well where I couldn't use this library with the Client SDK credentials and I'm trying to avoid having to use service account creds to give admin-level permission to my server.

I ended up implementing what I needed in `NodeJS` instead since there is both an admin library (`firebase-admin`) and a client library (`firebase`) on there.

It would really be helpful if we could figure out the same sort of thing for Python libraries.

**Comment by LeonardoRick** [comment]
@vindard I did the same and I think it's the only viable solution. I needed to create this `middleware node` for my python client app, and all firebase requests goes throw this `node` program I'm delivering with my application and is settle up with `firebase` client libraty. This way I can ensure that the client requests are respecting firestore rules

**Comment by tseaver** [comment]
@LeonardoRick I'm afraid I don't understand your use case here.  The client needs to be initialized with credentials, which you can pass to it explicitly, rather than using the implicit environmental search for credentials.  E.g.:

```python
from google.oauth2.service_account import Credentials
from google.cloud.firestore_v1 import Client

credentials = Credentials.from_service_account_info({<your creds info here>})
fs = Client(credentials=credentials)
```

Please reopen / follow up if this example does not address your question.
