### ISSUE TITLE
Implemente .initialize_app() as a true client app, that needs user authentication to login and respect firestore rules

### ISSUE THREAD

**Issue by LeonardoRick** [googleapis/python-firestore#314]
Its very sad to be able to do a lot of things with a client app on web and Android, but not with python. Since python do not have an API to authenticate users, the only way to connect with the API is by giving the user full access to the Firebase repo and sending him the private.key from the project, what certainly must not be done.

A solution to that sould be to do exactly what Pyrebase does, but it's only related to Realtime DB, so do not achieve my porpuse neither.

A solution would be to be able to connect to Client() with something like this:

```
config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com"
}

fs = Client().initialize_app(config)
```

**Comment by LeonardoRick** [comment]
I opened it as a feture request, don't know if I should do that but I followed [this instructions](https://stackoverflow.com/questions/66125484/connect-to-firestore-using-python-as-client-with-limited-permissions?noredirect=1#comment116943585_66125484)

**Comment by crwilcox** [comment]
Thanks for reaching out @LeonardoRick.

The Firestore SDK doesn't have deep knowledge of firebase as the relationship is that firebase leverage Firestore, not the other way around. For that reason, I would expect to see such a feature to show up in the [Firebase Admin SDK](https://github.com/firebase/firebase-admin-python)

This said, have you looked at https://firebase.google.com/docs/admin/setup#python_1 already? Does this meet your requirements? It closely resembles it so I wonder if using that SDK instead (which embeds this one) would work.

**Comment by LeonardoRick** [comment]
the main instructions page on this link: https://firebase.google.com/docs/admin/setup#python_1 says as an observation that `cloud firestore` do not work with oauth2. All instructions are kind of mixed up and it's hard to know watch aproacah to follow.

So, talking about this current repository, there's no way to connect with firestore considering it's rules? If so, theres no way to use the library outside a server, which kind of takes from firebase whats the best from him (serverless)

**Comment by crwilcox** [comment]
Cloud Firestore does not support authentication via Firebase auth directly. A common approach is to create a Cloud Function that contains Firestore calls and processing.

https://firebase.google.com/docs/functions

**Comment by LeonardoRick** [comment]
Using cloud functions takes out the simplicity of the real-time updates reflecting everywhere on the application. It takes so much more time to make a http request on every single and little update I make on a document.

Is there any plans to add this feature? I wish I could help with that but I don't think enough knowledge to do so.

**Comment by samtstern** [comment]
@LeonardoRick Sam from the Firebase team here. I want to clarify this issue because your underlying request is valid but the way it's posed doesn't actually add up.

So Firebase has two kinds of SDKs:

- **Client SDKs** - meant to be used by an end user in an untrusted environment, like a mobile device. These SDKs use Firebase Authentication credentials to authenticate and they also generally assume the user has a slow or unreliable connection to Google data centers.  We make these SDKs for Android, iOS, Web, Unity, and C++.
- **Admin SDKs** - meant to be used by your server in a trusted environment, like your server. These SDKs use Google Cloud service account credentials to authenticate and they generally assume that the user has a fast and reliable connection to Google data centers.  We make these SDKs for Node, Python, Go, Java, .NET, etc.

Both of these SDK types are built on top of the same Firestore REST/RPC API which will accept both kinds of credentials and apply the right access controls for each credential type.

So in this library what *could* change is that the library could allow you to pass in a Firebase Auth ID token instead of a service account credential and everything would "just work" from an authentication perspective. You'd be responsible for getting a new token every hour (via the Firebase Auth REST API) but that's not too hard.

However what is much harder to change is the non-auth behavior differences. Because this SDK is designed as an "Admin" SDK to be used from a server it uses different RPC methods for things like transactions and realtime listening. If you were to use this SDK in an end-user application like a Python desktop app or a mobile app things would probably break. Plus there would be no offline caching, no latency compensation, etc. In general it would not be a very good experience!

**Comment by LeonardoRick** [comment]
@samtstern thanks for answering. I wasn't aware that this library was designed as an Admin SDK. Actually I often use [firebase-admin-python](https://github.com/firebase/firebase-admin-python) to do this kind of operations, so I taught that maybe this library was supposed to be something more related to the client side. 

I'll close the issue since this is really not related to this repo and would not be nice to use it as a desktop app. My solution was to build a node middleware between my python application, and all the firebase requests go throw this node client. It's not the perfect solution but it's working for me.

Just to conclude, would be awesome if we had a python client library! Thanks for the support.
