### ISSUE TITLE
Request for auth

### ISSUE THREAD

**Issue by ChrisChross** [googleapis/python-firestore#356]
Hey guys,

first of all, thanks for this great API.

Actually this is more of a question than a request.
I recently started to use firestore cloud and pretty much like it. 
What i find quite confusing though, is all the different versions of APIs and not a really speration of them (in my opinion).
So i struggled a little but but get some clearity now. Anyways, my question is the following:

How could i query user specific date with the auth key (uid) i received after logging in? 
As i see so far, there is no way to pass it along the query, what I would like to have is the following:

```python
db.collection('books').document("Faust").update({"Author":"Goethe"}, **uid**)
```
just passing the parameter to reference to a specific user.
Or is there any easier way to get only user specific (referenced by authorization) data back ?

Similar to:
````
var user = firebase.auth().currentUser;

db.collection("stories").where("author", "==", user.uid).get()
````

Also i am missing some basic functions such as loginWithEmailAndPassword, Reset password usw. 

Best regards 
Chris

**Comment by craiglabenz** [comment]
Hey Chris! Thanks for this question. There are a few pieces of info that, together, I think will get you moving again.

First, once a user is logged in, client SDKs will securely send their unique `uid` along with all ensuing requests. This is particularly useful for any Cloud Functions you may interact with, or for security rules. [Here is a great video on how to think about security rules](https://www.youtube.com/watch?v=eW5MdE3ZcAw).

Secondly, as Firestore is a non-relational database, there aren't any ways to *concretely* tell Firestore that certain data applies to certain records. But all is not lost, because you can still do this yourself simply by mirroring that `user.uid` value inside relevant documents elsewhere in your database. For example, imagining a typical `comments` collection, you might have fields like this:

```json
{
  "body": "<the comment written by the author>",
  "post": "<post_id>",
  "author": {
    "uid": "<the value grabbed from the authorized user's `uid`>",
    "username": "<denormalized username>",
    "profile_picture": "<denormalized profile picture>"
  },
  "createdAt": "<current time in UTC>"
}
```

Then, when it comes time to show all the comments written by a given user, you are able to query for which comments' `author.uid` field matches your currently authenticated user's `uid` value.

[Here's a great tutorial for how to think about linking data to authenticated users](https://www.youtube.com/watch?v=qWy9ylc3f9U).

And lastly, for any collections that are sensitive, it's important to verify queries with security rules, as that will disallow malicious users from spoofing `user.uid` values and reading other users' sensitive data.

Hope that helps!

(PS - I'm going to close this for now, but feel free to re-open if you have any further questions!)
