### ISSUE TITLE
Firestore limit_to_last(n) returns the first n elements in a reverse order instead of returning the last n elements

### ISSUE THREAD

**Issue by brenhr** [googleapis/python-firestore#536]
### Describe your environment
- SDK version: 2.3.4
- Python version: 3.10.2
- Pip version: 21.2.4

### Describe the problem

As per the documentation for [limit_to_last](https://googleapis.dev/python/firestore/latest/query.html#google.cloud.firestore_v1.base_query.BaseQuery.limit_to_last)[](https://user-images.githubusercontent.com/36976556/152664681-5e3d23f8-9298-491b-9a81-d6aeeb08bdf0.png) clause, it should return the last n elements that match the query. However, when executing a simple query (i.e. `db.collection("numbers").order_by("number").limit_to_last(5)`) it returns the first 5 elements but in a reverse order.

### Steps to reproduce
Create a collection and add data (in my case, I created a "numbers" collection, and inserted a total of 50 documents (from number 0 to 49) as follows:
```
for i in range(50):
    db.collection('numbers').document(f'{i}').set({
        'number': i
    })
```

And then, execute the following query and print the results:
```
lastDocs = db.collection('numbers').order_by("number").limit_to_last(5).get()
print('Last docs [using limit_to_last() clause]')

for doc in lastDocs:
    print(f'{doc.to_dict()}')
```

##### Expected output:
```
Last docs [using limit_to_last() clause]
{'number': 45}
{'number': 46}
{'number': 47}
{'number': 48}
{'number': 49}
```

##### Real output:
<img width="810" alt="Screen Shot 2022-02-05 at 19 32 46" src="https://user-images.githubusercontent.com/36976556/154746550-83fde19c-8c44-4c0b-9213-588ad8fd8d4a.png">

In case you find it useful, I also tried to reproduce this behavior in the [Node.js Admin SDK](https://github.com/firebase/firebase-admin-node)[](https://user-images.githubusercontent.com/36976556/152664660-fb76d042-1b96-4714-ac2c-b3972cd229f5.png), and I obtained the desired output (I mean, limitToLast() works perfectly fine):
Node.js code:
```
var numbersRef = db.collection("numbers");

console.log("Last documents [using limitToLast()]:");

numbersRef.orderBy("number").limitToLast(5).get().then((snapshot) => {
  snapshot.docs.forEach(doc => {
    console.log(doc.data());
  })
});
```

Node.js output:
<img width="793" alt="Screen Shot 2022-02-05 at 19 31 26" src="https://user-images.githubusercontent.com/36976556/154746609-30105bc7-749d-43dd-8933-540906227689.png">

Thanks.

**Comment by dconeybe** [comment]
The limit-to-last implementation in python-firestore is broken when startAt, endAt, startAfter, or endBefore is specified. The reason is that the implementation must flip these "cursors", _in addition to_ flipping the ordering, and the implementation only flips the ordering:

https://github.com/googleapis/python-firestore/blob/6480f6a274b1b51271d103ba7212ed83ac9c665e/google/cloud/firestore_v1/query.py#L153-L163

Here is the example of the correct implementation from the nodejs-firestore SDK:

https://github.com/googleapis/nodejs-firestore/blob/a67a12470c2238e6c03f9613de147c525eb7cae5/dev/src/reference.ts#L2147-L2159

**Comment by dconeybe** [comment]
The good news is that there is a relatively-easy workaround. Limit-to-last queries are implemented entirely in the client, and do not need any special server support. This means that you can implement limit-to-last yourself to work around this bug.

Here is an example. The code below is all pseudocode for simplicity, not real Python code.

Suppose you have these documents in your database:
* doc1 age=1
* doc2 age=2
* doc3 age=3
* doc4 age=4
* doc5 age=5
* doc6 age=6

Suppose you wanted to do limitToLast(3).orderBy("age", "ASC").endBefore(doc5), which would produce the result [doc2, doc3, doc4].

You could instead run this query: limit(3).orderBy("age", "DESC").startAfter(doc5). This query would produce the result [doc4, doc3, doc2] so the final step would be to reverse the order of the result set, to [doc2, doc3, doc4].

**Comment by Mariatta** [comment]
The bug is due to this line

https://github.com/googleapis/python-firestore/blob/6480f6a274b1b51271d103ba7212ed83ac9c665e/google/cloud/firestore_v1/query.py#L158

The test `order.direction == self.ASCENDING` is not correct, and always returns `False`, therefore the order was never properly updated.
`order.direction` is an enum whereas self.ASCENDING is a type `str`. I've just opened a PR https://github.com/googleapis/python-firestore/pull/692
