### ISSUE TITLE
Support DocumentSnapshot cursors

### ISSUE THREAD

**Issue by schmidt-sebastian** [googleapis/python-firestore#56]
The Python client should add support for DocumentSnapshot-based cursors.

See https://github.com/googleapis/java-firestore/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java#L853 or https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/reference.ts#L1663

**Comment by HemangChothani** [comment]
@schmidt-sebastian As per my research i think python supports `DocumentSnapshot-based cursors`,  but the confusion is just because of naming convention, will update the name of the parameter so it could minimize the confusion.Let me know if i misunderstood anything or missing something.
https://github.com/googleapis/python-firestore/blob/b1c5987c606a14874b412e70f93015e161e278d6/google/cloud/firestore_v1/query.py#L460
https://github.com/googleapis/python-firestore/blob/b1c5987c606a14874b412e70f93015e161e278d6/google/cloud/firestore_v1/query.py#L475-L480

**Comment by schmidt-sebastian** [comment]
@HemangChothani Sorry, I missed this completely. Would it be possible to rename `document_fields`? That name caught my eyes and I immediately thought Python does not support these cursors. 

The reason I looked at this was to figure out whether the Python SDK considers "IN" filters to be equality cursors. I am not able to decipher the code to provide an answer (https://github.com/googleapis/python-firestore/blob/b1c5987c606a14874b412e70f93015e161e278d6/google/cloud/firestore_v1/query.py#L627). Only the operations GREATER_THAN, GREATER_THAN_OR_EQUALS, LESS_THAN or LESS_THAN_OR_EQUALS should be used to compute the implicit cursor. See also the fix here: https://github.com/googleapis/java-firestore/pull/216. Do we need to port this fix?

**Comment by HemangChothani** [comment]
> Would it be possible to rename `document_fields`?

@schmidt-sebastian Yes, I have opened a PR https://github.com/googleapis/python-firestore/pull/58




>  Do we need to port this fix?

I think  "IN" filter is not considered as a equality cursors. If i compare the python code it is similar to the old java code, but still need a conformation.

This line is not going to execute for `==` and `array_contains` operator.

https://github.com/googleapis/python-firestore/blob/b1c5987c606a14874b412e70f93015e161e278d6/google/cloud/firestore_v1/query.py#L636-L637

For better view i think need to concern @crwilcox

**Comment by HemangChothani** [comment]
@crwilcox Any suggestion on `Python SDK considers "IN" filters to be equality cursors`?

**Comment by HemangChothani** [comment]
@schmidt-sebastian I thinks this issue is resolved and only the operations GREATER_THAN, GREATER_THAN_OR_EQUALS, LESS_THAN or LESS_THAN_OR_EQUALS should be used to compute the implicit cursor.
As we can see here:
https://github.com/googleapis/python-firestore/blob/be988971cc1bbbc3616a849037dafc8cc0bb5745/google/cloud/firestore_v1/base_query.py#L682-L689

so closing this issue for now, feel free to reopen if it doesn't fulfill the requirements.

**Comment by schmidt-sebastian** [comment]
Sounds good. Thanks for clarifying and sorry for the confusion.
